export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const INCREMENT = 'INCREMENT'

export const FILTER_ARTICLE = 'FILTER_ARTICLE'

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'

export const CHANGE_SELECTION = 'CHANGE_SELECTION'
